### ISSUE TITLE
voicemail.pstore appears in the root directory when running specs

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/voicemail#2] opened 2012-10-26 22:33 UTC
As well as tmp/voicemail.pstore

**Comment by lpradovera** [comment] 2012-10-30 14:49
I could not reproduce this, even with sleep() added to specs in case it was just a transitory issue.
I suppose you just ran "bundle exec rspec"?

**Comment by benlangfeld** [comment] 2012-10-30 18:00
bundle exec guard -c

Regards,
Ben Langfeld

Em 30 Oct 2012, às 12:49, polysics notifications@github.com escreveu:

I could not reproduce this, even with sleep() added to specs in case it was
just a transitory issue.
I suppose you just ran "bundle exec rspec"?

—
Reply to this email directly or view it on
GitHubhttps://github.com/adhearsion/voicemail/issues/2#issuecomment-9908317.

**Comment by lpradovera** [comment] 2012-10-30 21:04
Not with that either. Maybe you had an old file somehow?

**Comment by JustinAiken** [comment] 2013-09-05 21:50
I haven't seen this pop up at all, and I've been working on this gem a lot lately... Closing for now, will reopen if anyone else sees it pop up at any point.

**Closed as completed by JustinAiken** 2013-09-05 21:50 UTC
Labels: bug
